// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_high_scores = "CgkI0tCG4PoeEAIQAQ"; // <GPGSID>
        public const string achievement_cleared_stage_1 = "CgkI0tCG4PoeEAIQAg"; // <GPGSID>
        public const string achievement_cleared_stage_2 = "CgkI0tCG4PoeEAIQAw"; // <GPGSID>
        public const string achievement_cleared_stage_3 = "CgkI0tCG4PoeEAIQBA"; // <GPGSID>
        public const string achievement_cleared_stage_4 = "CgkI0tCG4PoeEAIQBQ"; // <GPGSID>
        public const string achievement_cleared_stage_5 = "CgkI0tCG4PoeEAIQBg"; // <GPGSID>

}

