// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_twins_stage_4 = "CgkIvo2m9KEXEAIQBQ"; // <GPGSID>
        public const string achievement_twins_stage_5 = "CgkIvo2m9KEXEAIQBg"; // <GPGSID>
        public const string leaderboard_twins_high_cores = "CgkIvo2m9KEXEAIQAQ"; // <GPGSID>
        public const string achievement_twins_stage_1 = "CgkIvo2m9KEXEAIQAg"; // <GPGSID>
        public const string achievement_twins_stage_2 = "CgkIvo2m9KEXEAIQAw"; // <GPGSID>
        public const string achievement_twins_stage_3 = "CgkIvo2m9KEXEAIQBA"; // <GPGSID>

}

